#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Author: Seokjun Moon
# For Turtlebot3 AutoRace 2021

import rospy
from std_msgs.msg import UInt8, String

class NextMission():
    mission_list = ['intersection', 'construction', 'parking', 'level_crossing', 'tunnel', 'TheEnd']
    mission_num = 0
    cnt = 0

    def callback(self, data):
        if (self.mission_num == 0):
            if (data.data == 2 or data.data == 3):
                self.cnt += 1

                if (self.cnt == 5):
                    self.mission_num += 1
                    self.cnt = 0
                    rospy.loginfo("Next Mission is %s", self.mission_list[self.mission_num])
        elif (self.mission_num <= 4):
            if (data.data == 1):
                self.cnt += 1

                if (self.cnt == 5):
                    self.mission_num += 1
                    self.cnt = 0
                    rospy.loginfo("Next Mission is %s", self.mission_list[self.mission_num])

                    if (self.mission_num > 4):
                        self.pub.publish(self.mission_list[self.mission_num])
                        rospy.loginfo("All Mission is cleared")
                        rospy.signal_shutdown("All Mission is cleared")

    def main(self):
        self.pub = rospy.Publisher('pub_next_mission', String, queue_size=1)
        rospy.Subscriber('/detect/traffic_sign', UInt8, self.callback, queue_size=1)
        
        rate = rospy.Rate(10) # 10hz 
        while not rospy.is_shutdown():
            mission_str = self.mission_list[self.mission_num]
            self.pub.publish(mission_str)
            rate.sleep()

if __name__ == '__main__':
    try:
        rospy.init_node('pub_next_mission', anonymous=True)
        node = NextMission()
        node.main()
    except rospy.ROSInterruptException:
        rospy.loginfo("Error occurred")
        pass
